### ISSUE TITLE
Thesis index page

### ISSUE THREAD

**Issue by hnykda** [ea-czech-republic/efektivnialtruismus.cz#53]
https://cacoo.com/diagrams/t0dRXcF8boiE4Hug#7A1A4
![image](https://user-images.githubusercontent.com/2741256/36078850-3b1ab70a-0f7c-11e8-9b5e-0e59261b732b.png)

- [x] remove editable model field which is not used
- [x] only one button with `How to choose a topic`
- [x] 3 columns with header + text (editable)
- [x] single stream field below (text, process headline, text 2, donate button as a HTML snippet)

Optional:
- [ ] references below columns
- [ ] arrow to `choose your topic` (not needed)

**Comment by hnykda** [comment]
https://github.com/ea-czech-republic/efektivnialtruismus.cz/pull/56/commits/602d56b715f981ec2bf3d12858cf8bcac722377a

**Comment by DavidJanku** [comment]
looks good! if you could add the "optional" points, it would be great and I can add the real text right away

**Comment by hnykda** [comment]
Then I need to know:

1. how many references we have and their length (may look weird if they are unbalance)
2. `choose your topic` arrow, similarly as in https://github.com/ea-czech-republic/efektivnialtruismus.cz/issues/54#issuecomment-354497880 feels really weird to me. Why couldn't you use the menu `Topic` element? IMO, not repeating control elements is preferable (so there is one way how to get to a place) and should be violated only when absolutely necessary. The current proposal - having the arrow on the bottom right side is also going to cause issues such as spacing and a responsive behavior.

**Comment by DavidJanku** [comment]
1) 2 references, from singer and daniel, see the end of [this document](https://docs.google.com/document/d/1D9xnTra3kySZP8rqfjQoj96kudDQ6fkPAcLcHv6WQUs/edit#heading=h.cvm3kyh3zo9j) - the reference from Max Daniel seems to be a bit longer, but he said we can edit it however we want. Do you want me to edit it so both references have the same number of characters or is it ok like this?
2) the point was to make it more visible to users that they can go directly to choosing their topics from landing page and dont have to click through the articles they might have already read. However, your point is good, I need to discuss it with some expert to conclude whether people who are re-visiting would intuitively press the menu Topic element.

**Comment by hnykda** [comment]
Summary:

# Content
delivered by @DavidJanku 

- [ ] shortened version of references
- [ ] numbers (hours, projects, ...)
- [ ] what text where

Process:  from http://effectivethesis.com/project/ under `Process`

# Functionality
delivered by hnykda

- [ ] link to the list of the topics

**Comment by DavidJanku** [comment]
References: 
1) Too many students write theses that achieve nothing other than meet the requirement for the degree they are seeking. When there are so many important questions, in a wide range of fields, that need to be answered, that's a terrible waste of time and intelligent, creative energy.  The Effective Thesis Project is seeking to change that, and I hope it will.

Peter Singer, Ira W. DeCamp Professor of Bioethics at Princeton University, Laureate Professor at the University of Melbourne

2) The Effective Thesis project is a great way to make high-impact research areas more visible to university students...This would have an outsized social impact - especially because the Effective Thesis project has carefully selected its suggested topics based on cutting-edge research from the emerging field of global priorities research.

Max Daniel, executive director of the Foundational research institute

—- is that short enough? If not, I’ll have to ask for new versions of references, because I don’t have an idea how to shorten it more

Numbers: as it is (and make it editable in admin if possible)

What text where:

Under references, this is all the text that follows:

The Effective Thesis project aims to focus research on areas that have the potential to greatly improve the world. A lot of skilled and talented people at universities find themselves in a situation where they have to write a large final thesis (bachelor, diploma, Ph.D.) at least once during their studies. Many of them find it difficult to choose a topic and end up giving much time and effort into a paper that only serves as a means to get their degree, with almost no subsequent applications. But when there is so much energy invested in the thesis, why not choose a topic that will, on the top of gaining you a diploma, benefit and help someone else?

We have collected a list of topics from socially beneficial organizations related to the Effective Altruism community, which deal with some of the most pressing global issues. To ensure highest possible quality and utility of students’ work, we have agreed with organizations to provide consultations to students. That way students can draw from another source of information and be sure that if they write a high-quality thesis, their work and effort will be made use of to make the world a better place.

Process (ideally in points)

After you choose your topic, click the "I want this topic" button and send us your information. 
We then ask you to write a research proposal describing how you would like to work on the topic. That should help you to start thinking about the topic more deeply and establish a plan to approach the topic. Based on this proposal we can also provide feedback in the early stages of working on the topic. If there are multiple candidates for one topic, it would also help us to choose which candidate to connect with the organization who created the topic. The proposal may involve a description of methodological approach as well as any specific ideas student already has about the topic. The more precise the description and argumentation, the better. It shouldn’t be longer than two A4 pages. 
After that, we connect you with the organization, send them your details and your proposal. You arrange regular consultations with them to ensure that your work is going in the right direction and to help you with some theoretical (and maybe even practical) uncertainties. 
At this point you should also start looking for a teacher at your course who will be your supervisor. It always helps if the mentor has deep understanding of the relevant topic, thus would provide insightful guidance.
Thereafter, it's all up to you. We won't interfere in your communication with the organization, but if you need any help, we'll try to do our best. After you defend your thesis, we'll send you a few questions exploring your experience with this project and connection with the organization. With your permission, we'll also publish your thesis on our websites.  



The Effective Thesis project is run by volunteers in their free time ouside of work and studies, but as we are gaining tractions with more organizations and students involved, the project demands more time and even professional services (e.g. online marketing tools to address students) to be well maintained. Help us to improve this project, help more students to make use of their time and effort and more organizations to do even more good.

**Comment by hnykda** [comment]
Ok, so I filled that with the content, most of it is editable in admin, so you can try to play with that yourself. But I don't think it is functional. No one is going to read this:
![image](https://user-images.githubusercontent.com/2741256/36350883-3ce1a9ee-14a0-11e8-8ebf-13498c2581ad.png)
