### ISSUE TITLE
No theses appear without selecting a tag/s

### ISSUE THREAD

**Issue by Daver2910** [ea-czech-republic/efektivnialtruismus.cz#69]
![no post appear without tag seletion](https://user-images.githubusercontent.com/31806168/34676028-450e3142-f483-11e7-85f6-2cb0d6b6c136.PNG)

Location - http://effectivethesis.com/theses/

Should some of the theses appear below the tags without the user having to select subjects/tags first?
Maybe a student who has absolutely no idea what to write about would take advantage of this layout?
what do you think?

**Comment by DavidJanku** [comment]
thats actually intentional, because we found out that some users dont select their disciplines at all and just start scrolling down through the content that is not relevant to them at all, increasing chances of being put off by irrelevance of the website.
Logically, it makes sense that user first uses filters to make content more relevant, not using filters doesnt make sense and doesn't bring any value.
